### ISSUE TITLE
大佬，为什么安装不了呢

### ISSUE THREAD

**Issue by ADolphin-02** [Xposed-Modules-Repo/cn.kwaiching.hook#1]
手机型号：realme gt neo3
安卓版本：12
下载最新apk，安装的时候报错

![Screenshot_2022-11-23-16-46-09-50_bb8ece83317b06ec453d187d61792a56](https://user-images.githubusercontent.com/55866634/203503938-b10d584b-a9bd-41e8-9752-6149565e8575.jpg)

**Comment by YuzakiSio** [comment]
我也是

**Comment by Hleison** [comment]
我也是，显示解析安装包错误

**Comment by ratsan** [comment]
Because it is an aab not apk. Use bundletool to build apk or use my build - [Download](https://nekofile.eu.org/cc733ec26bc10ff601af8rk61)

**Comment by kwaiching** [comment]
網盤有所有版本的app, 去網盤下
