### ISSUE TITLE
密码是什么，已捐赠

### ISSUE THREAD

**Issue by pdg666** [Xposed-Modules-Repo/cn.kwaiching.hook#13]
求助联系不上啊

**Comment by kwaiching** [comment]
支付賬單那有聯繫商家, 或直接加QQ;微信;支付寶好友; 備註訂單號

**Comment by ffplayer** [comment]
> 支付賬單那有聯繫商家, 或直接加QQ;微信;支付寶好友; 備註訂單號

请问下 一般多久会有回复？支付宝联系商家和飞机联系都没回应

**Comment by kwaiching** [comment]
支付寶每天在線
